---
- hosts: all
  tasks:
    - name: Checkout Repo
      git:
        repo: https://github.com/thomaslorentsen/python-of-things.git
        dest: /home/tom/python-of-things
        update: yes
      notify: Restart Service
  post_tasks:
    - name: Wait for service to start
      wait_for:
        port: 5000
        delay: 3
    - name: Service is up
      debug:
        msg: "Service has started listening"
  handlers:
    - name: Restart Service
      become: yes
      supervisorctl:
        name: pyhttp
        state: restarted
